package com.project.labs.nutrigrow.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF00BF63)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFFFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF000000)
val md_theme_light_secondaryContainer = Color(0xFF00BF63)
val md_theme_light_onSecondaryContainer = Color(0xFFFFFFFF)
val md_theme_light_tertiary = Color(0xFF9C404D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFFFFF)
val md_theme_light_onTertiaryContainer = Color(0xFF000000)
val md_theme_light_error = Color(0xFFFD3232)
val md_theme_light_errorContainer = Color(0xFFF1E7E6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFFFFFFF)
val md_theme_light_onSurfaceVariant = Color(0xFF575555)
val md_theme_light_outline = Color(0xFFC5BEB9)
val md_theme_light_inverseOnSurface = Color(0xFFF6EDFF)
val md_theme_light_inverseSurface = Color(0xFF3A1D71)
val md_theme_light_inversePrimary = Color(0xFFFFB786)
val md_theme_light_surfaceTint = Color(0xFF954900)
val md_theme_light_outlineVariant = Color(0xFFD7C3B7)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_background = Color(0xFFFCFCFC)

val md_theme_dark_primary = Color(0xFFFFB786)
val md_theme_dark_onPrimary = Color(0xFF502400)
val md_theme_dark_primaryContainer = Color(0xFF723600)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDCC6)
val md_theme_dark_tertiary = Color(0xFFFFB2B9)
val md_theme_dark_onTertiary = Color(0xFF5F1222)
val md_theme_dark_tertiaryContainer = Color(0xFF7D2937)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDADC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_surfaceVariant = Color(0xFF52443C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C3B7)
val md_theme_dark_outline = Color(0xFF9F8D83)
val md_theme_dark_inversePrimary = Color(0xFF954900)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB786)
val md_theme_dark_outlineVariant = Color(0xFF52443C)
val md_theme_dark_scrim = Color(0xFF000000)

//Reference
val custom_green1 = Color(0xFF79B519)
val custom_green2 = Color(0xFFD6FFC4)
val custom_blue = Color(0xFF49ACFC)
val custom_cyan = Color(0xFF81FFE3)

val BrandGreen = Color(0xFF00BF63)
val BrandGreenSoft = Color(0xFFE0FFD2)
val SurfaceCard = Color(0xFFFFFFFF)
val FieldOutline = Color(0xFF9DA1A6)
val TextPrimary = Color(0xFF000000)
val TextSecondary = Color(0xFF575555)
val TextMuted = Color(0xFF757575)
