package com.project.labs.nutrigrow.ui.state

fun wfaAdvice(status: String): String = when (status) {
    "Normal" ->
        "Balita dengan status gizi berat badan normal perlu mempertahankan pola makan seimbang dengan variasi makanan yang beragam. Berikan makanan dari semua kelompok gizi: karbohidrat, protein, lemak, vitamin, dan mineral dalam proporsi yang tepat. Jadwal makan teratur 3 kali makan utama dan 2 kali camilan sehat. Dorong konsumsi sayuran dan buah-buahan berwarna-warni, protein dari sumber hewani dan nabati, serta karbohidrat kompleks. Batasi makanan tinggi gula, garam, dan lemak jenuh. Pastikan kebutuhan air putih terpenuhi dan aktivitas fisik yang cukup untuk mendukung pertumbuhan optimal dan mencegah kelebihan berat badan."
    "Underweight" ->
        "Balita dengan status gizi berat badan kurang membutuhkan peningkatan asupan kalori dan protein untuk mencapai berat badan ideal. Berikan makanan bergizi tinggi dengan porsi yang disesuaikan kemampuan makan anak. Fokus pada protein berkualitas tinggi seperti telur, ikan, ayam, dan kacang-kacangan. Kombinasikan dengan karbohidrat kompleks dan lemak sehat. Berikan camilan bergizi di antara waktu makan utama, seperti buah-buahan, yogurt, atau biskuit yang diperkaya. Pastikan asupan vitamin dan mineral cukup melalui sayuran berwarna dan buah-buahan. Pantau perkembangan berat badan secara rutin dan konsultasikan dengan ahli gizi jika diperlukan."
    "Severely Underweight" ->
        "Balita dengan status gizi berat badan sangat kurang memerlukan intervensi nutrisi intensif dan segera. Kebutuhan kalori harian perlu ditingkatkan secara bertahap dengan fokus pada makanan padat energi dan protein tinggi. Berikan makanan dalam porsi kecil namun sering, sekitar 6-8 kali sehari. Prioritaskan protein hewani seperti telur, ikan, daging, dan susu, serta karbohidrat kompleks seperti nasi, kentang, dan ubi. Tambahkan lemak sehat dari alpukat, minyak zaitun, atau kacang-kacangan. Hindari makanan tinggi serat yang dapat membuat anak cepat kenyang. Konsultasi dengan tenaga kesehatan sangat diperlukan untuk evaluasi penyebab dan rencana pemulihan yang tepat."
    "Risk of Overweight" ->
        "Balita dengan status berisiko berat badan lebih belum tentu mengalami masalah gizi, tetapi perlu dipastikan lebih lanjut. Indeks BB/U tidak dapat membedakan berat badan lebih karena kelebihan lemak dari berat badan lebih karena tubuh yang memang tinggi, sehingga hasilnya wajib dikonfirmasi dengan indeks BB/TB. Bila BB/TB menunjukkan gizi baik, cukup pertahankan pola makan seimbang dan pemantauan rutin setiap bulan. Bila BB/TB juga menunjukkan berisiko gizi lebih, mulailah membatasi makanan dan minuman tinggi gula serta lemak jenuh, perbanyak sayuran dan buah, dan tingkatkan aktivitas bermain aktif. Hindari diet ketat pada balita karena dapat mengganggu pertumbuhan, dan konsultasikan dengan tenaga kesehatan sebelum melakukan pembatasan makanan."
    else -> "Data tidak lengkap"
}

fun hfaAdvice(status: String): String = when (status) {
    "Normal" ->
        "Balita dengan status gizi tinggi badan normal perlu mempertahankan asupan nutrisi seimbang untuk mendukung pertumbuhan linier yang optimal. Berikan variasi makanan yang mengandung protein, kalsium, vitamin D, dan mikronutrien lainnya. Pastikan asupan susu atau produk susu yang cukup untuk mendukung pertumbuhan tulang. Berikan sayuran hijau, buah-buahan, dan sumber protein yang beragam. Jaga pola makan teratur dan hindari kebiasaan makan yang dapat mengganggu penyerapan nutrisi. Aktivitas fisik yang cukup juga penting untuk merangsang pertumbuhan tulang. Lakukan pemantauan pertumbuhan secara berkala untuk memastikan pertumbuhan tetap dalam jalur yang baik."
    "Stunted" ->
        "Balita dengan status gizi pendek membutuhkan asupan nutrisi yang optimal untuk memaksimalkan potensi pertumbuhan tinggi badan. Prioritaskan makanan sumber protein hewani yang mengandung asam amino lengkap seperti telur, ikan, ayam, dan susu. Kombinasikan dengan protein nabati dari kacang-kacangan dan biji-bijian. Pastikan asupan mikronutrien penting seperti zinc, zat besi, kalsium, dan vitamin A melalui daging, hati, sayuran hijau, dan buah-buahan berwarna orange. Berikan makanan yang mudah dicerna dan diserap tubuh. Hindari faktor yang dapat menghambat penyerapan nutrisi seperti infeksi berulang. Konsultasi dengan tenaga kesehatan untuk memastikan tidak ada masalah kesehatan yang mendasari."
    "Severely Stunted" ->
        "Balita dengan status gizi sangat pendek memerlukan intervensi nutrisi yang intensif dan berkelanjutan untuk mengoptimalkan pertumbuhan linier yang tersisa. Berikan makanan tinggi protein berkualitas seperti telur, ikan, daging, dan produk susu untuk mendukung pertumbuhan tulang dan otot. Pastikan asupan kalsium, fosfor, vitamin D, dan zinc yang cukup melalui susu, keju, sayuran hijau, dan kacang-kacangan. Berikan makanan padat energi dalam porsi kecil namun sering. Hindari makanan yang dapat menghambat penyerapan nutrisi. Suplementasi vitamin dan mineral mungkin diperlukan sesuai anjuran dokter. Konsultasi dengan ahli gizi dan dokter anak secara rutin untuk evaluasi dan modifikasi rencana nutrisi sangat penting."
    "Tall" ->
        "Balita dengan status tinggi termasuk sangat tinggi menurut umurnya. Pada sebagian besar kasus keadaan ini bukan masalah, terlebih bila orang tuanya juga bertubuh tinggi, dan tidak memerlukan pembatasan makanan apa pun. Lanjutkan pemberian makanan bergizi seimbang serta pemantauan pertumbuhan setiap bulan. Yang perlu diperhatikan adalah bila tinggi badan anak melaju jauh melampaui tinggi kedua orang tuanya, karena keadaan itu sesekali menandakan gangguan endokrin, misalnya tumor yang memproduksi hormon pertumbuhan. Bila hal tersebut dicurigai, rujuk anak ke dokter spesialis anak untuk pemeriksaan lebih lanjut."
    else -> "Data tidak lengkap"
}

fun wfhAdvice(status: String): String = when (status) {
    "Normal" ->
        "Balita dengan proporsi berat badan sesuai tinggi badan perlu mempertahankan keseimbangan nutrisi untuk menjaga komposisi tubuh yang optimal. Berikan makanan seimbang dari semua kelompok gizi dengan porsi yang tepat. Pastikan asupan protein cukup untuk mempertahankan massa otot, karbohidrat untuk energi, dan lemak sehat untuk perkembangan otak. Berikan variasi sayuran dan buah-buahan untuk memenuhi kebutuhan vitamin dan mineral. Jaga pola makan teratur dan hindari makanan berlebihan yang dapat menyebabkan kelebihan berat badan. Dorong aktivitas fisik yang sesuai usia untuk mempertahankan keseimbangan energi dan mendukung perkembangan motorik."
    "Wasting" ->
        "Balita dengan status gizi kurang membutuhkan peningkatan asupan energi dan protein untuk memulihkan massa tubuh yang hilang. Berikan makanan padat energi seperti nasi dengan minyak, alpukat, kacang-kacangan, dan protein hewani. Fokus pada makanan yang mudah dicerna dan tinggi kalori. Berikan camilan bergizi tinggi di antara waktu makan seperti susu, biskuit yang diperkaya, atau smoothie buah dengan susu. Pastikan asupan vitamin dan mineral cukup untuk mendukung metabolisme dan pemulihan. Hindari makanan yang dapat mengganggu nafsu makan atau pencernaan. Pantau perkembangan berat badan secara rutin dan sesuaikan porsi makanan sesuai kemajuan."
    "Severely Wasting" ->
        "Balita dengan status gizi buruk berada dalam kondisi akut yang memerlukan penanganan medis segera. Berikan makanan tinggi kalori dan protein dengan fokus pada pemulihan massa otot dan lemak tubuh. Makanan harus mudah dicerna seperti bubur yang diperkaya protein, susu, dan minyak. Berikan makanan dalam porsi kecil namun sangat sering, setiap 2-3 jam. Prioritaskan makanan terapeutik seperti RUTF (Ready-to-Use Therapeutic Food) jika tersedia. Hindari makanan tinggi serat yang dapat membuat kenyang tanpa memberikan kalori cukup. Pemantauan medis ketat diperlukan untuk mendeteksi dan mengatasi komplikasi. Konsultasi dengan dokter anak dan ahli gizi untuk rencana rehabilitasi nutrisi yang tepat."
    "Possible Risk of Overweight" ->
        "Balita dengan status berisiko gizi lebih belum tergolong gizi lebih, tetapi berat badannya sudah bergerak ke arah itu sehingga perlu dijaga sekarang, bukan nanti. Pada tahap ini yang diperlukan bukan penurunan berat badan, melainkan memperlambat pertambahannya sambil tinggi badan terus bertambah. Batasi minuman manis, jajanan kemasan, dan gorengan; ganti dengan air putih, buah potong, dan camilan berbahan pangan lokal. Pertahankan porsi makan utama yang wajar dan hindari memaksa anak menghabiskan makanan ketika sudah kenyang. Tingkatkan waktu bermain aktif setidaknya satu jam sehari dan batasi waktu layar. Timbang kembali bulan depan untuk memastikan arahnya membaik."
    "Overweight" ->
        "Balita dengan status gizi lebih memerlukan pengaturan pola makan untuk mencapai proporsi tubuh yang sehat. Kurangi asupan kalori dengan membatasi makanan tinggi lemak dan gula, namun tetap memenuhi kebutuhan nutrisi untuk pertumbuhan. Perbanyak konsumsi sayuran, buah-buahan, dan protein tanpa lemak. Berikan porsi makan yang lebih kecil dengan frekuensi yang cukup. Batasi minuman manis dan camilan tinggi kalori. Pilih camilan sehat seperti buah potong atau yogurt rendah lemak. Tingkatkan aktivitas fisik sesuai kemampuan anak. Konsultasi dengan ahli gizi untuk rencana pengendalian berat badan yang aman tanpa mengganggu pertumbuhan."
    "Obese" ->
        "Balita dengan status obesitas memerlukan penanganan oleh tenaga kesehatan, bukan hanya pengaturan makan di rumah. Obesitas pada usia dini meningkatkan risiko obesitas dan penyakit metabolik pada usia dewasa, sehingga perlu ditangani lebih awal. Rujuk anak ke puskesmas atau dokter anak untuk pemeriksaan menyeluruh, termasuk kemungkinan penyebab lain di luar pola makan. Sementara menunggu rujukan, hentikan pemberian minuman manis dan makanan cepat saji, ganti camilan dengan buah dan sayur, serta pastikan anak bergerak aktif setiap hari. Jangan menerapkan diet penurunan berat badan pada balita tanpa pengawasan tenaga kesehatan, karena pertumbuhan tinggi badan dan perkembangan otak masih berlangsung."
    else -> "Data tidak lengkap"
}
